https://api.giphy.com/v1/gifs/random?api_key=7vzU4y0lW9Jf9rW1KXFtVG2Vm9o8RsOb&tag=congratulatons&rating=g

### werkt niet

https://media2.giphy.com/media/1fm9a68tbJPVGmeidp/giphy.gif

### werkt wel
https://i.giphy.com/JRQ1PegFVKXBu.gif
